name = "Polylogarithms"
uuid = "43cc4a2f-1a2b-4fbb-87e3-95c794af13de"
authors = ["Matthew Roughan <matthew.roughan@adelaide.edu.au>"]
version = "0.2.0"

[deps]
IrrationalConstants = "92d709cd-6900-40b7-9082-c6be49f344b6"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
julia = "1.10"
SpecialFunctions = "2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[workspace]
projects = ["test", "docs", "data", "extended_tests"]

[targets]
test = ["Test"]

