[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
OpenSSL_jll = "458c3c95-2e84-50aa-8efc-19380b2a3a95"
Polylogarithms = "43cc4a2f-1a2b-4fbb-87e3-95c794af13de"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[sources]
Polylogarithms = {path = ".."}

[compat]
OpenSSL_jll = "3.0"
